### ISSUE TITLE
How Do I Revert To Gravatar?

### ISSUE THREAD

**Issue by ghost** [darcyclarke/pet-a-day-action#1]
@darcyclarke 

hey, bro. this isn't an issue with your project, so feel free to close this if you want.

anyhow, I'm not able to revert to Gravatar. I've mentioned this on a couple other Github issues and I can't seem to get any answers:

https://github.com/isaacs/github/issues/1909

https://github.com/isaacs/github/issues/1932

I would really appreciate some help. I only ask you because step 3 on your [Requirements section](https://github.com/darcyclarke/pet-a-day-action#requirements) says:

> If you've previously uploaded a profile image to GitHub, "Revert to Gravatar" (re. Settings > Profile > Edit)

However, I do not see that option. This is what I see:

![cant-revert-to-gravatar](https://s3.amazonaws.com/blog.avatarbox.io/images/cant-revert-to-gravatar.png)

Where's my option to `Revert to Gravatar`?

Thanks.

**Comment by darcyclarke** [comment]
@mrtillman-0000 🤔 hmmm, I believe, since you have a fairly new account, & haven't uploaded a photo yet that GitHub is actually using the Gravatar image at the moment already (so you don't have to "revert"); For the record, that pixelated image comes from Gravatar AFAIK. I'd double-check that your account is using the same email as your Gravatar, then potentially try uploading a temporary image (to GitHub) & reverting at that point to see if it helps... there's also a delay as far as I could tell when switching profile photos based on how we cache assets

**Comment by mrtillman-0000** [comment]
@darcyclarke 

hey, thanks for your reply. as I mentioned previously in the links to issues 1909 and 1932:

my public GitHub email is associated with a Gravatar icon, and in fact, you can confirm this by visiting https://en.gravatar.com/site/check/mantillman.0000@yahoo.com.

My Gravatar also works on GitLab: https://gitlab.com/mrtillman-0000

It just won't show on GitHub: https://github.com/mrtillman-0000

so, I'm sure my Gravatar icon is there, working properly. that pixelated image is actually a [GitHub Identicon](https://github.blog/2013-08-14-identicons) as you can see here: https://github.com/identicons/mrtillman-0000.png

I just don't know why it keeps loading the Identicon instead of my Gravatar icon. this seems like a small, simple, fixable issue, but it's turning into a real mystery.

**Comment by darcyclarke** [comment]
Like I said, try uploading an image and then see if you get the prompt to revert back to Gravatar. I'd also try using a different email

**Comment by ghost** [comment]
@darcyclarke 

ok, yep. btw, I can see the revert button after I upload an image, so that part is no longer a mystery.

thanks again for taking some time to reply.

**Comment by darcyclarke** [comment]
If, for whatever reason it still doesn't show your uploaded Gravatar image after you revert, I'd look into your email and make sure you haven't missed confirming ownership or activating your account somehow on GitHub's side... Maybe also you're using something like email+github@domain.com & expecting that to map to email@domain.com... Or maybe you changed your primary email at some point 🤷🏼‍♂️ just some ideas... Uploading and then reverting though should reset your profile image though
